apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stest-deployment
  labels:
    app: k8stest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8stest
  template:
    metadata:
      labels:
        app: k8stest
    spec:
      containers:
      - name: k8stest-deployment
        image: laolu/k8stest
        ports:
        - containerPort: 3000