apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stest-deployment
  labels:
    app: k8stest
spec:
  #How many copies of each pod do we want?
  replicas: 2
  #Which pods are managed by this deployment?
  selector:
   #This must match the labels we set on the pod!
    matchLabels:
      app: k8stest
  template:
    metadata:
      labels:
        app: k8stest
    spec:
      containers:
        - name: k8stest-container
          image: laolu/k8stest
          ports:
          #conatainerPort is actually optional ,Even without it your Service will know where to direct 
          #the request based on the info it has declared in its targetPort
            - containerPort: 3000 
