apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  name: k8stest-service
spec:
  selector:
  # Selector for Pods
    app: k8stest
  ports:
  # Port Map
      #The port of this service
      #Traffic comes in on nodePort, forwards to port on the service which then routes to targetPort on the pod(s).
    - port: 80
      #This is the actual port on which your application is running inside the container.
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer